development:
  adapter: mysql2
  encoding: utf8
  database: abandon_bikes_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: abandon_bikes_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>